### ISSUE TITLE
element-react/next should be precompiled

### ISSUE THREAD

**Issue by egoist** [eleme/element-react#349]
### Description

`import { Button } from 'element-react/next'` should work out of the box without manually configuring webpack/babel for element-react, currently it contains ES6 and flow annotations.

**Comment by e1emeb0t** [comment]
Flow annotations will be removed since the next npm release, but I think we should keep ES6 code to make sure **tree-shaking** works with `webpack 2` and `rollup.js`.

If you don't want to create extra configurations, you can import the ES5 version by this:
`import { Button } from 'element-react'`;

Any advises?

**Comment by egoist** [comment]
You can keep `import/export` syntax while compiling down to ES5.

**Comment by smallpath** [comment]
It seems that tree-shaking isn't working with current webpack2 and uglifyJS because of the [side effect](https://github.com/webpack/webpack/issues/2867). 

Until now, it's a better idea to use something like babel-plugin-transform-imports(transform import path to require real file) and babel-plugin-component(the element's default on-demand transformer, with extra ability to locate css file). 

Btw, webpack using a **module** field to make ES6 and ES5 precompiled files works together

**Comment by e1emeb0t** [comment]
> You can keep import/export syntax while compiling down to ES5.

@egoist I can't find a way to keep `import/export` with babel, is that an plugin?

**Comment by egoist** [comment]
I guess `modules: false` would work since you're using es2015 preset?

**Comment by e1emeb0t** [comment]
@egoist https://github.com/eleme/element-react/issues/368 may solve this issue.
